In [24]:
import pandas as pd
import json
import re
from collections import defaultdict

In [25]:
df = pd.read_csv(r"C:\Users\geeth\OneDrive\Desktop\ResumeIQ-AI-Resume-Screening-System\data\raw\ml_resume_dataset_4500.csv")

df.head()

,id,name,years_experience,highest_degree,skills,current_title,has_portfolio,raw_text,label
0,1,Badhan Shah,9,Bachelors,"NLP, GPT",Customer Support,False,Sales professional with strong communication s...,0
1,2,Lamia Sarker,2,Masters,"PyTorch, CI/CD, Power BI, Data Visualization, AWS",Administrative Assistant,False,Sales professional with strong communication s...,0
2,3,Badhan Molla,2,Bachelors,"AWS, Flask, Machine Learning, Model Deployment...",Computer Vision Engineer,True,Research scientist with strong statistical bac...,1
3,4,Badhan Ahmed,9,Bachelors,"Hadoop, Feature Engineering, Docker Compose, O...",Data Entry Operator,True,Customer support representative with some Exce...,0
4,5,Rasel Siddiqui,10,Bachelors,"Speech Recognition, Tableau, Azure, TensorFlow",Customer Support,False,Content creator interested in data science but...,0

In [26]:
print(df.columns)

print(df.shape)

df.head()

Index(['id', 'name', 'years_experience', 'highest_degree', 'skills',
       'current_title', 'has_portfolio', 'raw_text', 'label'],
      dtype='str')
(4500, 9)

,id,name,years_experience,highest_degree,skills,current_title,has_portfolio,raw_text,label
0,1,Badhan Shah,9,Bachelors,"NLP, GPT",Customer Support,False,Sales professional with strong communication s...,0
1,2,Lamia Sarker,2,Masters,"PyTorch, CI/CD, Power BI, Data Visualization, AWS",Administrative Assistant,False,Sales professional with strong communication s...,0
2,3,Badhan Molla,2,Bachelors,"AWS, Flask, Machine Learning, Model Deployment...",Computer Vision Engineer,True,Research scientist with strong statistical bac...,1
3,4,Badhan Ahmed,9,Bachelors,"Hadoop, Feature Engineering, Docker Compose, O...",Data Entry Operator,True,Customer support representative with some Exce...,0
4,5,Rasel Siddiqui,10,Bachelors,"Speech Recognition, Tableau, Azure, TensorFlow",Customer Support,False,Content creator interested in data science but...,0

In [38]:
skills_df = df[["current_title", "skills"]].copy()

skills_df.head()

              current_title                                             skills
0          Customer Support                                           NLP, GPT
1  Administrative Assistant  PyTorch, CI/CD, Power BI, Data Visualization, AWS
2  Computer Vision Engineer  AWS, Flask, Machine Learning, Model Deployment...
3       Data Entry Operator  Hadoop, Feature Engineering, Docker Compose, O...
4          Customer Support     Speech Recognition, Tableau, Azure, TensorFlow

In [36]:
df[["current_title", "label"]].head(20)

               current_title  label
0           Customer Support      0
1   Administrative Assistant      0
2   Computer Vision Engineer      1
3        Data Entry Operator      0
4           Customer Support      0
5        Data Entry Operator      0
6               Receptionist      0
7              AI Researcher      1
8                 Telecaller      0
9            Sales Executive      0
10        Research Scientist      1
11          Office Assistant      0
12     Senior Data Scientist      1
13             Junior Intern      0
14       Data Entry Operator      0
15              Receptionist      0
16          Customer Support      0
17  Computer Vision Engineer      1
18             AI Researcher      1
19     Senior Data Scientist      1

In [37]:
print(df["current_title"].nunique())
print(df["label"].nunique())

20
2

In [28]:
skills_df["skills"] = (
    skills_df["skills"]
    .str.lower()
    .str.replace(";", ",", regex=False)
    .str.replace("|", ",", regex=False)
)

skills_df.head()

   label                                             skills
0      0                                           nlp, gpt
1      0  pytorch, ci/cd, power bi, data visualization, aws
2      1  aws, flask, machine learning, model deployment...
3      0  hadoop, feature engineering, docker compose, o...
4      0     speech recognition, tableau, azure, tensorflow

In [39]:
role_skills = defaultdict(set)

for _, row in skills_df.iterrows():

    role = row["current_title"]

    skills = row["skills"].split(",")

    for skill in skills:

        skill = skill.strip()

        if skill:

            role_skills[role].add(skill)

In [40]:
role_skills = {

    role: sorted(list(skills))

    for role, skills in role_skills.items()

}

print("Total Roles:", len(role_skills))

Total Roles: 20

In [41]:
for role in list(role_skills.keys())[:10]:

    print("\n", role)

    print(role_skills[role][:15])

 Customer Support
['AWS', 'Azure', 'BERT', 'CI/CD', 'Classification', 'Clustering', 'Computer Vision', 'Data Engineering', 'Data Visualization', 'Deep Learning', 'Docker', 'Docker Compose', 'EDA', 'FastAPI', 'Feature Engineering']

 Administrative Assistant
['AWS', 'Azure', 'BERT', 'CI/CD', 'Classification', 'Clustering', 'Computer Vision', 'Data Engineering', 'Data Visualization', 'Deep Learning', 'Docker', 'Docker Compose', 'EDA', 'FastAPI', 'Feature Engineering']

 Computer Vision Engineer
['AWS', 'Azure', 'BERT', 'CI/CD', 'Classification', 'Clustering', 'Computer Vision', 'Data Engineering', 'Data Visualization', 'Deep Learning', 'Docker', 'Docker Compose', 'EDA', 'FastAPI', 'Feature Engineering']

 Data Entry Operator
['AWS', 'Azure', 'BERT', 'CI/CD', 'Classification', 'Clustering', 'Computer Vision', 'Data Engineering', 'Data Visualization', 'Deep Learning', 'Docker', 'Docker Compose', 'EDA', 'FastAPI', 'Feature Engineering']

 Receptionist
['AWS', 'Azure', 'BERT', 'CI/CD', 'Classification', 'Clustering', 'Computer Vision', 'Data Engineering', 'Data Visualization', 'Deep Learning', 'Docker', 'Docker Compose', 'EDA', 'FastAPI', 'Feature Engineering']

 AI Researcher
['AWS', 'Azure', 'BERT', 'CI/CD', 'Classification', 'Clustering', 'Computer Vision', 'Data Engineering', 'Data Visualization', 'Deep Learning', 'Docker', 'Docker Compose', 'EDA', 'FastAPI', 'Feature Engineering']

 Telecaller
['AWS', 'Azure', 'BERT', 'CI/CD', 'Classification', 'Clustering', 'Computer Vision', 'Data Engineering', 'Data Visualization', 'Deep Learning', 'Docker', 'Docker Compose', 'EDA', 'FastAPI', 'Feature Engineering']

 Sales Executive
['AWS', 'Azure', 'BERT', 'CI/CD', 'Classification', 'Clustering', 'Computer Vision', 'Data Engineering', 'Data Visualization', 'Deep Learning', 'Docker', 'Docker Compose', 'EDA', 'FastAPI', 'Feature Engineering']

 Research Scientist
['AWS', 'Azure', 'BERT', 'CI/CD', 'Classification', 'Clustering', 'Computer Vision', 'Data Engineering', 'Data Visualization', 'Deep Learning', 'Docker', 'Docker Compose', 'EDA', 'FastAPI', 'Feature Engineering']

 Office Assistant
['AWS', 'Azure', 'BERT', 'CI/CD', 'Classification', 'Clustering', 'Computer Vision', 'Data Engineering', 'Data Visualization', 'Deep Learning', 'Docker', 'Docker Compose', 'EDA', 'FastAPI', 'Feature Engineering']

In [42]:
output_path = "../data/processed/role_skills.json"

with open(output_path, "w") as file:

    json.dump(role_skills, file, indent=4)

print("Role skills saved successfully!")

Role skills saved successfully!

In [43]:
with open("../data/processed/role_skills.json", "r") as file:

    loaded_skills = json.load(file)

print("Total Roles:", len(loaded_skills))

list(loaded_skills.keys())[:10]

Total Roles: 20

['Customer Support',
 'Administrative Assistant',
 'Computer Vision Engineer',
 'Data Entry Operator',
 'Receptionist',
 'AI Researcher',
 'Telecaller',
 'Sales Executive',
 'Research Scientist',
 'Office Assistant']

In [44]:
loaded_skills.keys()

dict_keys(['Customer Support', 'Administrative Assistant', 'Computer Vision Engineer', 'Data Entry Operator', 'Receptionist', 'AI Researcher', 'Telecaller', 'Sales Executive', 'Research Scientist', 'Office Assistant', 'Senior Data Scientist', 'Junior Intern', 'Data Analyst', 'Applied ML Engineer', 'ML Engineer', 'Data Scientist', 'Marketing Intern', 'Content Writer', 'NLP Engineer', 'Machine Learning Engineer'])

In [49]:

list(loaded_skills.keys())

['Customer Support',
 'Administrative Assistant',
 'Computer Vision Engineer',
 'Data Entry Operator',
 'Receptionist',
 'AI Researcher',
 'Telecaller',
 'Sales Executive',
 'Research Scientist',
 'Office Assistant',
 'Senior Data Scientist',
 'Junior Intern',
 'Data Analyst',
 'Applied ML Engineer',
 'ML Engineer',
 'Data Scientist',
 'Marketing Intern',
 'Content Writer',
 'NLP Engineer',
 'Machine Learning Engineer']

In [50]:
for key in loaded_skills.keys():
    print(key)

Customer Support
Administrative Assistant
Computer Vision Engineer
Data Entry Operator
Receptionist
AI Researcher
Telecaller
Sales Executive
Research Scientist
Office Assistant
Senior Data Scientist
Junior Intern
Data Analyst
Applied ML Engineer
ML Engineer
Data Scientist
Marketing Intern
Content Writer
NLP Engineer
Machine Learning Engineer